---
- name: Set Bash Duplicate Handling
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^HISTCONTROL=.*$'
    line: 'HISTCONTROL=ignoreboth'
    state: present

- name: Set Bash History Appending
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^shopt -s histappend$'
    line: 'shopt -s histappend'
    state: present

- name: Set Bash History Size
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^HISTSIZE=\d+$'
    line: "HISTSIZE={{ bash_max_history }}"
    state: present

- name: Set Bash History File Size
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^HISTFILESIZE=\d+$'
    line: "HISTFILESIZE={{ bash_max_filesize }}"
    state: present

- name: Set Bash History Ignore List
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^HISTIGNORE=.*$'
    line: "HISTIGNORE='ls:history'"
    state: present

- name: Set Bash Collapse Multiline Command
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^shopt -s cmdhist$'
    line: 'shopt -s cmdhist'
    state: present

- name: Store and Reload Bash History Immediately
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bashrc"
    regexp: '^PROMPT_COMMAND=.*$'
    line: 'PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"'
    state: present
